[package]
name = "mless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
tonic = "0.11"
prost = "0.12"
prost-types = "0.12.3"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.8.0", features = ["v6", "std", "rng"] }
mac_address = "1.1.5"

[build-dependencies]
tonic-build = "0.11"